CREATE DATABASE `studentfeesystem` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

CREATE TABLE `fee_accountant` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` varchar(400) DEFAULT NULL,
  `LASTNAME` varchar(400) DEFAULT NULL,
  `EMAIL` varchar(400) DEFAULT NULL,
  `PASSWORD` varchar(400) DEFAULT NULL,
  `ADDRESS` varchar(400) DEFAULT NULL,
  `CONTACT` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `fee_student` (
  `ROLLNO` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  `EMAIL` varchar(45) DEFAULT NULL,
  `SEX` varchar(45) DEFAULT NULL,
  `COURSE` varchar(400) DEFAULT NULL,
  `FEE` int DEFAULT NULL,
  `PAID` int DEFAULT NULL,
  `DUE` int DEFAULT NULL,
  `ADDRESS` varchar(400) DEFAULT NULL,
  `CONTACT` varchar(400) DEFAULT NULL,
  PRIMARY KEY (`ROLLNO`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


